[twitch.auth]
client_id = 'YOUR_CLIENT_ID'
client_secret = 'YOUR_CLIENT_SECRET'
redirect_uri = 'http://localhost:8777' # must match HOST/PORT in [socket] 

[twitch.info]
channel = 'YOUR_CHANNEL_NAME' # must be lowercase
bot_account = 'YOUR_BOT_NAME'
channel_id = ''

[twitch.scopes]
bot_scope = 'chat%3Aread+chat%3Aedit'
broad_scope = 'channel%3Amanage%3Apredictions+moderation%3Aread'

[messages]
pred_begin_message = '🎰🚨🎰BETS ARE OPEN, any gamblers? modCheck 🎰🚨🎰'
pred_reminder_message = '🚨30 seconds left VeryPog make your bets NOW🚨'
pred_lock_prefix = '🎰BETS ARE CLOSED🎰'
pred_lock_suffix = 'PauseFish'
pred_winner_prefix = 'GIGACHAD'
pred_loser_prefix = 'xdd'
pred_cancel_message = 'Prediction canceled SadgeCry'

[hotkeys]
enabled = true

[socket]
host = '127.0.0.1' # localhost
port = 8777

[livesplit]
host = '127.0.0.1'
port = 16834
